import { findBestMatch } from "../countryMatcher";

const country = [
  "Miel",
  "Feral Interactive (Mac)",
  "Valve",
  "Winged Cloud",
  "Telltale Games",
  "PopCap Games, Inc.",
  "id Software",
  "Ubisoft Montreal",
  "Square Enix",
  "Feral Interactive (Linux)",
  "Firaxis Games",
  "CAPCOM Co., Ltd.",
  "Relic Entertainment",
  "Gearbox Software",
  "Quiet River",
  "GSC Game World",
  "Daedalic Entertainment",
  "CREATIVE ASSEMBLY",
  "Norn",
  "BioWare",
  "Traveller's Tales",
  "Team17 Digital Ltd",
  "Microids",
  "Croteam",
  "SEGA",
  "LucasArts",
  "Fulqrum Publishing",
  "Crystal Dynamics",
  "Capcom",
  "SimBin",
  "Raven Software",
  "Paradox Development Studio",
  "Nihon Falcom",
  "MicroProse Software, Inc",
  "Infinity Ward",
  "Double Fine Productions",
  "Codemasters",
  "Bethesda Game Studios",
  "Ryu Ga Gotoku Studio",
  "Rebellion",
  "Nightdive Studios",
  "NeocoreGames",
  "Klei Entertainment",
  "Frogwares",
  "Forever Entertainment S. A.",
  "Aspyr (Mac)",
  "Techland",
  "Cyanide Studio",
  "Bohemia Interactive",
  "Arkane Studios",
  "aNCHOR Inc.",
  "Zachtronics",
  "Wastelands Interactive",
  "Volition",
  "Visual Concepts",
  "Ubisoft Montpellier",
  "Treyarch",
  "Obsidian Entertainment",
  "Larian Studios",
  "KADOKAWA",
  "Haemimont Games",
  "Gotcha Gotcha Games",
  "Frontwing",
  "FromSoftware, Inc.",
  "Yoji Ojima",
  "SpinTop Games",
  "Spike Chunsoft Co., Ltd.",
  "Spiderweb Software",
  "Racing Bros",
  "QLOC",
  "ONEONE1",
  "Nadeo",
  "inXile Entertainment",
  "Gaijin Games",
  "Forgotten Empires",
  "EnsenaSoft",
  "DICE",
  "Dejobaan Games, LLC",
  "Crytek",
  "Avalanche Studios",
  "Assemble Entertainment",
  "Acerola",
  "11 bit studios",
  "TT Games",
  "Towndarktales",
  "Telltale",
  "Tale of Tales",
  "Supermassive Games",
  "Stardock Entertainment",
  "Spiders",
  "Sierra Entertainment",
  "Sierra",
  "Saber Interactive",
  "Realmforge Studios",
  "Pilgrim Adventures",
  "NovaLogic",
  "Introversion Software",
  "Gas Powered Games",
  "Funcom",
  "Frozenbyte",
  "Frontier Developments",
  "Eugen Systems",
  "Egosoft",
  "EA Los Angeles",
  "DONTNOD Entertainment",
  "Digital Extremes",
  "Cyanide Studios",
  "Core Design",
  "CD PROJEKT RED",
  "BANDAI NAMCO Studios Inc.",
  "ATLUS",
  "Aspyr (Linux)",
  "Arc System Works",
  "World's Edge",
  "Westwood Studios",
  "Ubisoft",
  "Two Tribes",
  "Triumph Studios",
  "Tripwire Interactive",
  "Total Mayhem Games",
  "Tindalos Interactive",
  "Team17",
  "Supergiant Games",
  "Spellbound",
  "Snkl Studio",
  "Sledgehammer Games",
  "Sierra Lee",
  "Rocksteady Studios",
  "Revolution Software Ltd",
  "Remedy Entertainment",
  "Reality Pump Studios",
  "Petroglyph",
  "Pendulo Studios",
  "Ninja Theory",
  "Might and Delight",
  "Looking Glass Studios",
  "KONAMI",
  "KING Art",
  "Irrational Games",
  "Illwinter Game Design",
  "Harebrained Schemes",
  "GrabTheGames Studios",
  "fuzz, Inc.",
  "Epic Games, Inc.",
  "Eidos-Montréal",
  "Digital Reality",
  "Dieselmine",
  "Deck Nine",
  "Coffee Stain Studios",
  "City Interactive",
  "Astronomic Games",
  "Artefacts Studio",
  "Ankama Studio",
  "Animation Arts",
  "AMPLITUDE Studios",
  "Amanita Design",
  "ACE Team",
  "Access Software",
  "Abstraction Games",
  "4A Games",
  "2K Australia",
  "Warfare Studios",
  "Wales Interactive",
  "Vlambeer",
  "Virtual Basement LLC",
  "Vile Monarch",
  "Vigil Games",
  "Vertigo Games",
  "Unknown Worlds Entertainment",
  "THQ Nordic",
  "Thomas Bowker",
  "The Chinese Room",
  "Team Reptile",
  "Streum On Studio",
  "Splash Damage",
  "Sonalysts",
  "Silent Dreams",
  "Shiro Games",
  "Shiny Shoe",
  "SCS Software",
  "SC Jogos",
  "Rockstar North",
  "Rockstar Games",
  "Robot Entertainment",
  "Ritual Games",
  "Ritual Entertainment",
  "Quantic Dream",
  "Pyro Studios",
  "PlatinumGames",
  "Piranha Bytes",
  "Pandemic Studios",
  "Owlchemy Labs",
  "Oddworld Inhabitants",
  "New Reality Games",
  "NetherRealm Studios",
  "Muse Games",
  "Moon Studios GmbH",
  "Monte Cristo",
  "Monolith Productions, Inc.",
  "Matthew Brown",
  "MachineGames",
  "Landfall",
  "KOEI TECMO GAMES CO., LTD.",
  "Jutsu Games",
  "Jackbox Games, Inc.",
  "IO Interactive A/S",
  "Inceton Games",
  "Hopoo Games",
  "High Voltage Software",
  "Hello There Games",
  "Gunfire Games",
  "General Arcade",
  "Gamesforgames",
  "Free Lives",
  "Firefly Studios",
  "Fatshark",
  "exosyphen studios",
  "Ensemble Studios",
  "Edmund McMillen",
  "Dovetail Games",
  "Digitalmindsoft",
  "Deck13",
  "Daybreak Game Company",
  "Cipher Prime Studios",
  "CI Games",
  "Blendo Games",
  "baron sengia",
  "Arrowhead Game Studios",
  "34BigThings srl",
  "343 Industries",
  "07th Expansion",
  "ZOOM Platform Media",
  "WayForward",
  "ViNovella Games",
  "Unicorn Games Studio",
  "Undead Labs",
  "Tribute Games Inc.",
  "Toxic Games",
  "Toge Productions",
  "Tin Man Games",
  "Timegate",
  "Tilted Mill Entertainment, Inc.",
  "The Lordz Games Studio",
  "The Behemoth",
  "Terry Cavanagh",
  "Tequila Works",
  "Tate Multimedia",
  "Targem Games",
  "Tantalus Media",
  "TaleWorlds Entertainment",
  "Swing Swing Submarine",
  "Suspicious Developments",
  "SUPERHOT Team",
  "Sumo Digital",
  "Stunlock Studios",
  "Spearhead Games",
  "Spark Unlimited",
  "SNK CORPORATION",
  "SMG Studio",
  "Slightly Mad Studios",
  "Sleepy Duck",
  "SkyGoblin",
  "Size Five Games",
  "Sierra On-Line",
  "Rusty Lake",
  "Runic Games",
  "Ronimo Games",
  "Roll7",
  "Robot Gentleman",
  "Reverie World Studios",
  "Red Thread Games",
  "Red Storm Entertainment",
  "Q-Games Ltd.",
  "PopTop",
  "Playful Corp.",
  "PiGravity",
  "Passtech Games",
  "Outerlight Ltd.",
  "Orange_Juice",
  "One More Level",
  "Noio",
  "Nixxes",
  "Nitro Games",
  "Nicalis, Inc.",
  "Mossmouth",
  "MicroProse Software",
  "MercurySteam",
  "Mediatonic",
  "Massive Damage, Inc.",
  "Little Orbit",
  "Labyrinthine",
  "Krillbite Studio",
  "Kheops Studio",
  "KAIKO",
  "Jordan Freeman Group",
  "Jesse Makkonen",
  "Ishtar Games",
  "Ion Storm",
  "Io-Interactive A/S",
  "IO Interactive",
  "Instinct Games",
  "Ino-Co Plus",
  "Impressions Games",
  "Image & Form Games",
  "Ice-Pick Lodge",
  "Hidden Path Entertainment",
  "Hello Games",
  "Hasoyua",
  "Hangar 13",
  "Grace Bruxner",
  "Games Farm",
  "FuturLab",
  "Frictional Games",
  "Flying Wild Hog",
  "Feral Interactive (Mac/Linux)",
  "Feral Interactive",
  "Elephant Games",
  "Drinkbox Studios",
  "Double Eleven",
  "Dotemu",
  "Deep Silver Volition",
  "Dead Mage",
  "Dancing Dragon Games",
  "D-Pad Studio",
  "Cygames, Inc.",
  "Curve Studios",
  "Crytek Studios",
  "Crew Lab",
  "Colossal Order",
  "Clymenia",
  "Climax Studios",
  "Circle Poison",
  "Circle Fairy Flower",
  "CINEMAX GAMES",
  "CAPCOM CO., LTD",
  "Byzantine Games",
  "Bugbear Entertainment",
  "Broken Rules",
  "Bossa Studios",
  "Boss Baddie",
  "Blue Byte",
  "Bloober Team SA",
  "Black Train",
  "Black Pants Studio",
  "Belgerum",
  "BananaKing",
  "Back To Basics Gaming",
  "AVANTGARDE",
  "attic Entertainment Software GmbH",
  "Asobo Studio",
  "Asakiyumemishi",
  "Arcen Games",
  "AQUAPLUS",
  "Anshar Studios",
  "Alientrap",
  "2K Marin",
  "ZOV GAME STUDIO",
  "Zootfly",
  "Zombie Studios",
  "Zetsubou",
  "Zen Studios",
  "Zeboyd Games",
  "Zeboyd Digital Entertainment LLC",
  "Yumenamakon",
  "Xaviant",
  "Wolfire Games",
  "Wishes Ultd.",
  "WildTangent",
  "Warhorse Studios",
  "Vostok Games",
  "Vertigo Gaming Inc.",
  "Vega Castañeda",
  "Vanguard Games",
  "United Independent Entertainment",
  "United Front Games",
  "Undergrad Steve",
  "Ubisoft Toronto",
  "Ubisoft Quebec",
  "Ubisoft Paris",
  "Ubisoft Bucharest",
  "Ubisoft Shanghaï",
  "U-ROOM",
  "Tyler Glaiel",
  "Ty Taylor",
  "Twisted Pixel Games",
  "Turtle Rock Studios",
  "Turquoise Revival Games",
  "Troika Games",
  "Triskell Interactive",
  "Trilobyte Games",
  "TreeFortress Games",
  "Transhuman Design",
  "Tomorrow Corporation",
  "Tiger Style",
  "Thunder Lotus",
  "Thorne Games",
  "The Game Bakers",
  "The Farm 51",
  "THE BROTHERHOOD",
  "The Binary Mill",
  "The Astronauts",
  "The Artistocrats",
  "Terrible Posture Games",
  "Terri Vellmann",
  "Terminal Reality",
  "Tennen-sozai",
  "Team Jolly Roger",
  "Team Cherry",
  "Tango Gameworks",
  "Syun-kan Flowlighter",
  "Subsoap",
  "Subset Games",
  "Subatomic Studios LLC",
  "Studio Wildcard",
  "Studio Pixel",
  "Studio II",
  "Strategy First",
  "Strange Loop Games",
  "Stranga Games",
  "Stoic",
  "State of Play",
  "Square Enix Montréal",
  "Spooky Doorway",
  "Space Cat Studios",
  "Soul Catapult",
  "Sos Sosowski",
  "Sokpop Collective",
  "SnowFlame",
  "Snowbird Games",
  "Snapshot Games Inc.",
  "Snail Games USA",
  "SmallSqurriel",
  "Slipgate Ironworks™",
  "SkyBox Labs",
  "SimTex",
  "Simogo",
  "Shimobashira Workshop",
  "Serenity Forge",
  "Sekerin Productions",
  "Secret Labo",
  "Secret Garden",
  "Sean Young",
  "Scavengers Studio",
  "Santa Ragione",
  "Runner Duck",
  "RosePortal Games",
  "Rogue Factor",
  "Rogue Entertainment",
  "Rodeo Games",
  "ROCKFISH Games",
  "Robert Briscoe",
  "RLR Training Inc",
  "Respawn Entertainment",
  "Remtairy",
  "Reflections, a Ubisoft Studio",
  "Red Dot Games",
  "Red Barrels",
  "Rain Games",
  "Radon Labs",
  "Radical Entertainment",
  "Radial Games Corp",
  "Psytec Games Ltd",
  "ProjectMoon",
  "Popcannibal",
  "Polyslash",
  "Pocketwatch Games",
  "Pocketpair",
  "PlayWay S.A.",
  "Playdead",
  "Pivotal Games",
  "Pinokl Games",
  "People Can Fly",
  "Paul Cuisset",
  "PanicBarn",
  "Panda Indie Studio",
  "OVERKILL - a Starbreeze Studio.",
  "Over the Top Games",
  "Other Ocean Interactive",
  "Ota Guchi Field",
  "OSome Studio",
  "Osmotic Studios",
  "Offworld",
  "Numantian Games",
  "NukGames",
  "NOVECT",
  "Nomad Games",
  "Nival",
  "Ninja Kiwi",
  "Night School Studio",
  "New World Interactive",
  "Nerial",
  "NEKO WORKs",
  "Neko Entertainment",
  "Narko Games",
  "Naked Sky Entertainment",
  "N-Fusion Interactive",
  "MPS Labs",
  "Movie Games Lunarium",
  "Mousechief",
  "Monolith Productions",
];

country.map((name) => {
  console.log({ iso2: findBestMatch(name)[0]?.iso2, name: name });
});
